In [1]:
%matplotlib inline
import matplotlib as mpl  
mpl.use('Agg')  
import numpy as np  
import matplotlib.pyplot as plt  
import gym
import numpy as np
#Load the environment
env = gym.make('FrozenLake-v0')
#Implement Q-Table learning algorithm
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
print "Score over time: " +  str(sum(rList)/num_episodes)
print "Final Q-Table Values"
print Q

/usr/lib64/python2.7/site-packages/matplotlib/__init__.py:1005: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
[2018-01-31 17:57:29,723] Making new env: FrozenLake-v0


Score over time: 0.487
Final Q-Table Values
[[9.89761092e-03 8.76637162e-01 1.28968877e-02 9.26261718e-03]
 [1.85064305e-03 1.58516791e-04 1.81982635e-04 2.59033429e-01]
 [1.06349404e-02 5.66063627e-03 6.28336467e-03 2.59056913e-01]
 [9.67817779e-03 3.58048090e-06 1.38930041e-04 1.91247691e-01]
 [8.85543757e-01 2.25758794e-03 1.56039843e-04 2.12518479e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.84727417e-01 7.65535876e-09 8.87755597e-05 2.54069133e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.77584179e-04 3.54561871e-04 2.14818401e-03 9.27162820e-01]
 [1.08060563e-03 9.78008673e-01 6.98071710e-05 1.12955578e-03]
 [9.89806895e-01 2.17481189e-04 4.39115229e-04 1.80747844e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.21249614e-04 9.52231864e-01 0.00000000e+00]
 [0.00000000e+00 9.94001005e-01 0.00000000e+00 0.00000000e+00]
 [0.0000000